### ISSUE TITLE
Wrong free space calculation

### ISSUE THREAD

**Issue by JacekDob** [nikband/check_qnap3.sh#17]
Input
`
./check_qnap3.sh 10.0.3.1 public volstatus 15 10
`

Output
`
Volume #1: OK: Ready, Total Size (bytes): 3.5 TB, Free: 1.2 TB (34%), Volume #2: OK: Ready, Total Size (bytes): 1.7 TB, Free: 80.4 GB (472%)|FreeSize_Volume-1=34%;15;10;0;100 FreeSize_Volume-2=472%;15;10;0;100
`

% is calculated based on digits only not taking into considiration units: in this case it divides 80.4GB/1.7TB and the result is 472%.

**Comment by nikband** [comment]
Hi Jacked I'll ckeck, it's not a good peace of code

I take from snmp: VOLCAPACITY and VOLFREESIZE that have different units, and for this problem UNITtest and UNITtest2 that i use for calculate correct value... 

may be this if it's not realy good  calculated... 
if [ "$UNITtest" == "TB" ]; then
	 factor=$(echo "scale=0; 1000" | bc -l)
	elif [ "$UNITtest" == "GB" ]; then
	 factor=$(echo "scale=0; 100" | bc -l)
	else
	 factor=$(echo "scale=0; 1" | bc -l)
fi

after calculate factor and factor2 

	VOLCAPACITYF=$(echo "scale=0; $VOLCAPACITY*$factor" | bc -l)
	VOLFREESIZEF=$(echo "scale=0; $VOLFREESIZE*$factor2" | bc -l)

        VOLPCT=`echo "($VOLFREESIZEF*100)/$VOLCAPACITYF" | bc`

i don't like the if string test... it's not realy good [ "$UNITtest" == "TB" ] 

On my qnap I have X TB and Y TB so it's difficult to test changes but i try 
Thanks for this issue! I would like to improve and make more efficient the script...

My english it's not realy good :( i try :D

**Comment by Zotteke** [comment]
I am experiencing a similar issue with the diskused command. I also get negative percentages.

Input: 
./check_qnap3.sh $HOSTNAME $COMMUNITY diskused 90 95 (I have replaced the names of the actual hostname and community for security reasons :-) )

Output:
OK: Total:5TB - Used:-56TB - Free:62GB - Used Space: -1065%|Used=-1065;90;95;0;100

Actual values are the following: 
Total space: SNMPv2-SMI::enterprises.24681.1.2.17.1.4.1 = STRING: "5.35 TB"
Free space: SNMPv2-SMI::enterprises.24681.1.2.17.1.5.1 = STRING: "623.47 GB"

If I check the web interface of the NAS I can see that he has 4.74TB in use of the 5.35TB. 
Is it possible to check this?

If you need extra information from me so you can check the issue, please let me know.

**Comment by nikband** [comment]
May be fixed by a contributor! Can you try the actual main script? Let me know... and sorry for big delay

**Comment by Zotteke** [comment]
I can happily report that the negative values have disappeared with the new main script and the percentages of the disk space used correspond with the percentages I see on the web pages of the devices.

He does still round the numbers so 1.2TB becomes 1TB. Will this be fixed in the future? (Not so big of a deal since the percentages are already ok :-) But it would be nicer to see the exact number ;-)

For now I do want to thank you for this script!! It is a great help!

**Comment by nikband** [comment]
Good i check this approssimation, the calc include all values so for check there is no problem but "visible" it's not the best... ;) Thanks for feedback!
