### ISSUE TITLE
volstatus always returns critical

### ISSUE THREAD

**Issue by mir07** [nikband/check_qnap3.sh#2]
```
 619         if [ "$VOLPCT" -le "$strCritical" ]; then
 620                 VOLPCT="CRITICAL: $VOLPCT"
 621                 CRITICAL=1
 622         elif [ "$VOLPCT" -le "$strWarning" ]; then
 623                 VOLPCT="WARNING: $VOLPCT"
 624                 WARNING=1
 625         fi
```
As long as VOLPCT < strCritical this check will return critical state. Should use >= to return correct state like:
```
619         if [ "$VOLPCT" -ge "$strCritical" ]; then
620                 VOLPCT="CRITICAL: $VOLPCT"
621                 CRITICAL=1
622         elif [ "$VOLPCT" -ge "$strWarning" ]; then
623                 VOLPCT="WARNING: $VOLPCT"
624                 WARNING=1
625         fi
```

**Comment by nikband** [comment]
Hi Mir07, 

For if check: in my nagios configuration i use: volstatus!20!15

if is X <= strCritical so X <=15  --> CRITICAL
if is X <= strWarning so X <=20 --> WARNING
if X > strWarinig it's OK 
Is the free space, so if the freespace is 5% you need to clear file... if is 60% there are no problem...

Let me know if you found some strange in this... (sorry for my English)

The CRITICAL=1 value WARNING=1 is for this final check:
     if [ $CRITICAL -eq 1 ]; then
        exit 2
     elif [ $WARNING -eq 1 ]; then
        exit 1
     else
        exit 0
     fi

An example on my real NAS

Ok status: check with volstatus 40 10

OUPUT: Volume #1: OK: Ready, Total Size (bytes): 10.0 TB, Free: 6.4 TB (64%)|FreeSize_Volume-1=64%;40;10;0;100

Warning status: check with volstatus 70 10

OUTPUT: Volume #1: OK: Ready, Total Size (bytes): 10.0 TB, Free: 6.4 TB (WARNING: 64%)|FreeSize_Volume-1=WARNING: 64%;70;10;0;100

The volume it is OK but there are warining free space, the plugin exit with 1

Critical status: check with volstatus 10 70

OUTPUT: Volume #1: OK: Ready, Total Size (bytes): 10.0 TB, Free: 6.4 TB (CRITICAL: 64%)|FreeSize_Volume-1=CRITICAL: 64%;10;70;0;100

Exitstatus 2: the volume is not bad (raid) but there are no space... 

Let me know if this is ok

**Comment by mir07** [comment]
I must have misunderstand the instructions. I see it should check free space but I thought it checked used space. I have changed the check and now it is working. Sorry for the noise;-)

BTW. You can add TS-212 and TS-231P to the supported versions.
