### ISSUE TITLE
Fake OK Status

### ISSUE THREAD

**Issue by Bassysta** [nikband/check_qnap3.sh#24]
Hi.
Today on my Qnap Disk 2 on 4 was gone, Qnap said 2 thins:

1: Raid was corruped
2: Disk 2 was empty 

On nagios i've status OK, for him obvously is correct that some slot could be empty, but in this case the slot was not empty, the disk was gone and raid corrupted.

Hope i've explained me correctly, have a nice day.

**Comment by nikband** [comment]
sorry for the problem :( i have to rewrite some part of the script, you have some log ouput?
